Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2024
Var

parte, palavra: caracter

Inicio

    escreva("Digite uma palavra: ")
    leia(palavra)
    
    parte:= COPIA(palavra,2,3)

    escreval(parte)



Fimalgoritmo